feat: add welcome to the jungle scraper tool
Anko59/aiden-job-finder pull request #10
Opened 2024-05-06 15:58 UTC by Smirkey

2024-05-06 16:01 UTC, Smirkey commented on aiden_app/tools/utils/wtj_scraper.py
> +            "x-algolia-application-id": "CSEKHVMS53",
we could use selenium to refresh this, don't know if it's necessary though

2024-05-06 16:03 UTC, Smirkey commented on aiden_app/tools/wtj_scraper_tool.py
> +        return results
this is not satisfying nor ready to be merged, the tool will simply return its own data format which has nothing to do with indeed's
furthermore, we need to de duplicate offers maybe

2024-05-06 16:08 UTC, Anko59 requested changes
Main issue here is that Wtj scraper overwrites Indeed scraper

2024-05-06 16:08 UTC, Anko59 commented on aiden_app/tools/tool.py
> +    def tool_function(func: Self):
You sure func should be Self? My assumption would be Callable

2024-05-06 16:08 UTC, Anko59 commented on aiden_app/tools/utils/wtj_scraper.py
> +        headers = {
Can we shorten the headers here?

2024-05-06 16:08 UTC, Anko59 commented on aiden_app/tools/wtj_scraper_tool.py
> +        super().__init__("IndeedScraper")
Wrong name

2024-05-06 16:08 UTC, Anko59 commented on aiden_app/tools/wtj_scraper_tool.py
> +        self.add_tool("search_jobs", self.search_jobs_wrapper)
I don't see how this is gonna work. In the `ToolAggregator`, the last function with the same name (search_jobs) will overwrite the previous one.

2024-05-06 16:08 UTC, Anko59 commented on aiden_app/tools/tools.json
> +            "description": "Search the the internet for job offers. Ranked by newest first.",
We either need two separate tools for indeed and wttj scapers, or one unified tool with additional engineering .

2024-05-10 15:14 UTC, Anko59 commented on aiden_app/tools/utils/wtj_scraper.py
> +        params = {"hitsPerPage": 1000, "query": search_query, "aroundLatLng": latlng, "aroundRadius": 200000000000000, "page": page}
Are the results ranked by location ? Does the location even matter with such a large radius?

2024-05-10 15:16 UTC, Anko59 approved these changes

2024-05-12 20:05 UTC, Smirkey commented
Let's switch to #12

2024-05-12 20:05 UTC, closed without merging